# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_738_368_000                     # Feb 1, 2025 at 00:00 GMT
evm_version = "cancun"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.8.28"
fs_permissions = [{ access = "read", path = "./" }]


[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
gnosis = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
gnosis = "${RPC_URL}"
